<?php /* @var $this Inchoo_Tickets_Block_Tickets */ ?>
<?=$this->getMessagesBlock()->toHtml()?>
<?php $_tickets = $this->getTickets() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Tickets') ?></h1>
</div>

<!-- TODO: fix pager! -->
<?=$this->getPagerHtml(); ?>
<?php if ($_tickets->getSize()): ?>
    <table class="data-table" id="my-tickets-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Subject') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_tickets as $_ticket): ?>
            <tr>
                <td><?=Mage::helper('core')->quoteEscape($_ticket->getSubject())?></td>
                <td><?=Mage::helper('core')->quoteEscape($_ticket->getStatus())?></td>
                <td><span class="nobr"><?php echo $this->formatDate($_ticket->getTimestamp()) ?></span></td>
                <td class="a-center">
                    <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_ticket) ?>"><?php echo $this->__('View Ticket') ?></a>
                        <br>
                        <?php if ($_ticket->getStatus()=='Open'): ?>
                            <a href="<?php echo $this->getCloseUrl($_ticket) ?>"><?php echo $this->__('Close Ticket') ?></a>
                        <?php else: ?>
                            <a href="<?php echo $this->getOpenUrl($_ticket) ?>"><?php echo $this->__('Open Ticket') ?></a>
                        <?php endif ?>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?=$this->__('You have placed no tickets.')?></p>
<?php endif ?>

<br><br>

<form action="<?php echo $this->getUrl('inchoo/tickets/addTicket') ?>" method="post" id="form-validate" autocomplete="off">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Add Ticket') ?></h2>
        <ul class="form-list">
            <li>
                <label for="subject" class="required"><em>*</em><?php echo $this->__('Subject') ?></label>
                <div class="input-box">
                    <input type="text" name="subject" id="subject" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subject')) ?>" class="input-text required-entry validate-no-html-tags" />
                </div>
            </li>
            <li>
                <label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <input type="text" name="message" id="message" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Message')) ?>" class="input-text required-entry validate-no-html-tags" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>